### PR TITLE
(#18, #8) reformat in ESM style, dedupe code

### LINKED ISSUE #8: Convert bot to ESM
ESM is more readable

## Expected Behavior

currently the bot is build in CJS and should be using modern style ESM / ES2021

## Current Behavior

Bot is build in CJS

## Possible Solution

Convert it

### LINKED ISSUE #18: Deduplicate code in index, guild-commands and commands entrypoints
The functionality and pipeline is now duplicate making it hard to maintain this bot.

## Expected Behavior

It will share functions and choose the right functions using `yargs` CLI.

## Current Behavior

Currently the code is duplicated causing multiple versions and unnecessary complexity.

## Possible Solution

.

## Steps to Reproduce (for bugs)

.

## Context

Trying to keep the code maintainable.

### PR DESCRIPTION
**Pull request by davidzwa**
This reworks the bot into an ESM module instead of CJS. This was so rigorous that the rest of the code got a brush over it and tackled #18.

The new package.json now looks like:
``` 
  "scripts": {
    "start": "node src/index.js",
    "dev": "nodemon src/index.js --mode=dev",
    "commands": "node src/index.js --mode=global",
    "commands-guild": "node src/index.js --mode=guild"
  },
```  

I've installed `yargs` as a CLI parser, to be made stricter in future.

## Description

By converting to ESM, the bot's code is slightly more readable and modern.

```
  "type": "module",
```

## Related Issues

Fixes #8 and Fixes #18 

## Motivation and Context

We all love clean and reusable code ready for testing.

## How Has This Been Tested?

1) Mode `dev` (dev script): I've ran it till the TOKEN is rejected. This means the startup logic has run at least once and the database connection is established.
2) Mode `undefined` (start script): runs same as 1)
3) Mode `global` (commands script) runs with TOKEN rejection
4) Mode `purgeCommands` (commands:purge script) runs with GUILD_ID missing rejection
5) Mode `guild` (commands:guild script) runs with GUILD_ID missing rejection

## Startup log

```
[nodemon] restarting due to changes...
[nodemon] starting `node src/index.js --mode=dev`
Starting in mode: dev
Dynamically importing file from ./commands/admin/welcome.js
Dynamically importing file from ./commands/general/ping.js
DiscordAPIError[0]: 401: Unauthorized
    at SequentialHandler.runRequest (file:///C:/Users/david/Projects/NickNelson/node_modules/@discordjs/rest/dist/index.mjs:669:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async SequentialHandler.queueRequest (file:///C:/Users/david/Projects/NickNelson/node_modules/@discordjs/rest/dist/index.mjs:472:14)
    at async deployCommands (file:///C:/Users/david/Projects/NickNelson/src/nick-bot-commands.js:39:9)
    at async file:///C:/Users/david/Projects/NickNelson/src/index.js:32:3 {
    at REST.put (file:///C:/Users/david/Projects/NickNelson/node_modules/@discordjs/rest/dist/index.mjs:891:17)
    at deployCommands (file:///C:/Users/david/Projects/NickNelson/src/nick-bot-commands.js:39:26)
    at async file:///C:/Users/david/Projects/NickNelson/src/index.js:32:3
C:\Users\david\Projects\NickNelson\node_modules\discord.js\src\client\Client.js:237
    if (!token || typeof token !== 'string') throw new Error('TOKEN_INVALID');
                                                   ^

Error [TOKEN_INVALID]: An invalid token was provided.
    at Client.login (C:\Users\david\Projects\NickNelson\node_modules\discord.js\src\client\Client.js:237:52)
    at initBot (file:///C:/Users/david/Projects/NickNelson/src/nick-bot.js:89:18)
    at async file:///C:/Users/david/Projects/NickNelson/src/index.js:33:3 {
  [Symbol(code)]: 'TOKEN_INVALID'
```

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

File: src/constants.js [hunk 1]
```diff
@@ -0,0 +1,18 @@
+export const AppModes = {
+    dev: "dev",
+    purgeCommands: "purgeCommands",
+    global: "global",
+    guild: "guild"
+};
+
+const defaultDatabase = "nickdb";
```
Comment (mkevenaar) [inline src/constants.js:8]:
```suggestion
const defaultDatabase = "NickNelson";
```

File: src/constants.js [hunk 2]
```diff
@@ -0,0 +1,18 @@
...
+
+export const Constants = {
+    defaultMongoString: `mongodb://localhost:27017/${defaultDatabase}`,
+    sourceFolder: "src",
+    commandsFolder: "commands",
+    eventsFolder: "events",
```
Comment (mkevenaar) [inline src/constants.js:14]: would a `databaseFolder` make sense here?

File: src/events/guildMemberAdd.js [hunk 3]
```diff
@@ -1,69 +1,66 @@
...
-			let finalTitle = await welcomeTitle
-				.replace(/{user.ping}/g, `${member.user}`)
-				.replace(/{user.name}/g, `${member.user.username}`)
-				.replace(/{user.id}/g, `${member.user.id}`)
-				.replace(/{user.tag}/g, `${member.user.tag}`)
-				.replace(/{guild.name}/g, `${guild.name}`)
-				.replace(/{guild.id}/g, `${guild.id}`)
-				.replace(/{guild.totalUser}/g, `${guild.memberCount}`);
+        // Replace all valid tags
+        let finalTitle = welcomeTitle
```
Comment (mkevenaar) [inline src/events/guildMemberAdd.js:29]: If we are deduplicating, would it make sense to move these replace actions into an own function?

File: src/nick-bot-commands.js [hunk 4]
```diff
@@ -0,0 +1,47 @@
+import {findCommandFiles, getRestInstance} from "./shared.js";
```
Comment (mkevenaar) [inline src/nick-bot-commands.js:1]: rename the file to `bot-commands.js` to make the code / files the same on both bots (and possible future bots)?

File: src/nick-bot-commands.js [hunk 5]
```diff
@@ -0,0 +1,47 @@
...
+import {Routes} from "discord-api-types/v9";
+
+/**
+ * Purge all guild specific commands
+ * @returns {Promise<void>}
```
Comment (mkevenaar) [inline src/nick-bot-commands.js:6]: Did you leave the `@param` out of here on purpose? You added them on the `deployCommands`

File: src/nick-bot.js [hunk 6]
```diff
@@ -0,0 +1,90 @@
+import {getEnvConfig} from "./shared.js";
```
Comment (mkevenaar) [inline src/nick-bot.js:1]: rename to `bot.js` to make the code / files the same on both bots (and possible future bots)?

File: src/nick-bot.js [hunk 7]
```diff
@@ -0,0 +1,90 @@
...
+import {resolveChannel} from "./tools/tools.js";
+import {Constants} from "./constants.js";
+import {readdirSync} from "fs";
+
+const sourceFolder = Constants.sourceFolder;
+const eventsFolder = Constants.eventsFolder;
+const commandsFolder = Constants.commandsFolder;
+const jsExt = Constants.jsExt;
+
+function createDatabaseClient() {
```
Comment (mkevenaar) [inline src/nick-bot.js:13]:
```suggestion
function createDiscordClient() {
```

File: src/shared.js [hunk 8]
```diff
@@ -0,0 +1,78 @@
...
+    return yargs(process.argv).argv;
+}
+
+export function getEnvConfig() {
+    validateEnvConfigState();
+
+    let {CLIENT_ID, GUILD_ID, TOKEN, MONGODB} = process.env;
+
+    if (!MONGODB) {
+        MONGODB = "mongodb://127.0.0.1:27017/nickdb";
```
Comment (mkevenaar) [inline src/shared.js:41]:
```suggestion
        MONGODB = "mongodb://127.0.0.1:27017/NickNelson";
```

Comment (mkevenaar) [reply src/shared.js:41]: Also should this not be using the default database name anyway?

**Review by mkevenaar — CHANGES_REQUESTED** [review]
Hi @davidzwa thank you for your work!

There are some things that I think that need to be changed. Also shouldn't there be changes to the files in the database folder?

File: src/constants.js (hunk 1 above)
Comment (davidzwa) [reply src/constants.js:8]: Fix upcoming in next commit ^^

File: src/events/guildMemberAdd.js (hunk 3 above)
Comment (davidzwa) [reply src/events/guildMemberAdd.js:29]: I tried to touch these files as little as possible to keep the impact of this PR sort-of contained. I do not oversee this file and we dont have coverage :/

Comment (davidzwa) [reply src/events/guildMemberAdd.js:29]: I tried to touch these files as little as possible to keep the impact of this PR sort-of contained. I do not oversee this file and we dont have coverage :/

Comment (mkevenaar) [reply src/events/guildMemberAdd.js:29]: Perhaps a new issue would be in place for this.

File: src/shared.js (hunk 8 above)
Comment (davidzwa) [reply src/shared.js:41]: I saw it! Thanks.

File: src/commands/admin/welcome.js [hunk 9]
```diff
@@ -1,103 +1,101 @@
-const { SlashCommandBuilder } = require('@discordjs/builders');
-const { Permissions } = require('discord.js');
+import {SlashCommandBuilder} from "@discordjs/builders";
```
Comment (mkevenaar) [inline src/commands/admin/welcome.js:1]: You removed the Permissions here, it's used on L40

```
ReferenceError: Permissions is not defined
    at Module.execute (file:///D:/github/mkevenaar/NickNelson/src/commands/admin/welcome.js:40:45)
    at Client.<anonymous> (file:///D:/github/mkevenaar/NickNelson/src/nick-bot.js:53:27)
    at Client.emit (node:events:527:28)
    at InteractionCreateAction.handle (D:\github\mkevenaar\NickNelson\node_modules\discord.js\src\client\actions\InteractionCreate.js:74:12)
    at Object.module.exports [as INTERACTION_CREATE] (D:\github\mkevenaar\NickNelson\node_modules\discord.js\src\client\websocket\handlers\INTERACTION_CREATE.js:4:36)
    at WebSocketManager.handlePacket (D:\github\mkevenaar\NickNelson\node_modules\discord.js\src\client\websocket\WebSocketManager.js:351:31)
    at WebSocketShard.onPacket (D:\github\mkevenaar\NickNelson\node_modules\discord.js\src\client\websocket\WebSocketShard.js:444:22)
    at WebSocketShard.onMessage (D:\github\mkevenaar\NickNelson\node_modules\discord.js\src\client\websocket\WebSocketShard.js:301:10)
    at WebSocket.onMessage (D:\github\mkevenaar\NickNelson\node_modules\ws\lib\event-target.js:199:18)
    at WebSocket.emit (node:events:527:28)
```

Comment (davidzwa) [reply src/commands/admin/welcome.js:1]: Should be fixed now!

File: src/database/guild.service.js [hunk 10]
```diff
@@ -0,0 +1,20 @@
+import {GuildModel} from "./models/guild.js";
+
+export class GuildService {
```
Comment (mkevenaar) [inline src/database/guild.service.js:3]:
```suggestion
export class DatabaseService {
```
Also rename the file to `database.service.js` so we can have all database functions in one place?

File: src/events/guildMemberAdd.js (hunk 3 above)
Comment (davidzwa) [reply src/events/guildMemberAdd.js:31]: #21 covers this well enough

**Review by mkevenaar — CHANGES_REQUESTED** [review]

File: src/commands/admin/welcome.js [hunk 11]
```diff
@@ -1,103 +1,105 @@
...
+import {Permissions} from "discord.js";
+import {GuildService} from "../../database/guild.service.js";
```
Comment (mkevenaar) [inline src/commands/admin/welcome.js:3]: I don't think `GuildService` is required here?

**Review by mkevenaar — APPROVED** [review]
LGTM!

**Comment by mkevenaar** [comment]
@Lucxjo please review

File: src/commands/admin/welcome.js [hunk 12]
```diff
@@ -1,103 +1,104 @@
...
+        data.markModified('addons.welcome');
+        await data.save();
+    }
 
-		if (typeof image !== 'undefined' && image !== null) {
-			data.addons.welcome.image = image;
-			data.markModified('addons.welcome');
-			await data.save();
-		}
+    if (typeof enable !== 'undefined' && enable !== null) {
```
Comment (Lucxjo) [inline src/commands/admin/welcome.js:73]: Does this line need to be an equality check on `undefined` and `null` types? Or could it be simplified to `!enable`?

File: src/commands/admin/welcome.js [hunk 13]
```diff
@@ -1,103 +1,104 @@
...
+        data.markModified('addons.welcome');
+        await data.save();
+    }
 
-		if (typeof title !== 'undefined' && title !== null) {
-			data.addons.welcome.title = title;
-			data.markModified('addons.welcome');
-			await data.save();
-		}
+    if (typeof channel !== 'undefined' && channel !== null) {
```
Comment (Lucxjo) [inline src/commands/admin/welcome.js:79]: Similar to above, does this line need to be an equality check on `undefined` and `null` types? Or could it be simplified to `!channel`?

File: src/commands/admin/welcome.js [hunk 14]
```diff
@@ -1,103 +1,104 @@
...
+        data.markModified('addons.welcome');
+        await data.save();
+    }
 
-		if (typeof message !== 'undefined' && message !== null) {
-			data.addons.welcome.message = message;
-			data.markModified('addons.welcome');
-			await data.save();
-		}
+    if (typeof image !== 'undefined' && image !== null) {
```
Comment (Lucxjo) [inline src/commands/admin/welcome.js:85]: Similar to above, does this line need to be an equality check on `undefined` and `null` types? Or could it be simplified to `!image`?

File: src/commands/admin/welcome.js [hunk 15]
```diff
@@ -1,103 +1,104 @@
...
+        data.addons.welcome.image = image;
+        data.markModified('addons.welcome');
+        await data.save();
+    }
 
-		await interaction.reply({ content: 'Settings saved!', ephemeral: true });
-	},
+    if (typeof title !== 'undefined' && title !== null) {
```
Comment (Lucxjo) [inline src/commands/admin/welcome.js:91]: Similar to above, does this line need to be an equality check on `undefined` and `null` types? Or could it be simplified to `!title`?

File: src/commands/admin/welcome.js [hunk 16]
```diff
@@ -1,103 +1,104 @@
...
+        data.addons.welcome.title = title;
+        data.markModified('addons.welcome');
+        await data.save();
+    }
+
+    if (typeof message !== 'undefined' && message !== null) {
```
Comment (Lucxjo) [inline src/commands/admin/welcome.js:97]: Similar to above, does this line need to be an equality check on `undefined` and `null` types? Or could it be simplified to `!message`?

**Review by Lucxjo — COMMENTED** [review]
Sorry for the bit of copy/paste, I'm at work at the moment and just quickly logged in. PR looks good otherwise, just could you clear some bits up?

Thanks

File: src/commands/admin/welcome.js (hunk 12 above)
Comment (davidzwa) [reply src/commands/admin/welcome.js:73]: This is tracked by #21 because I think this is indeed not the way to go, well spotted and I completely agree.

File: src/database/database.service.js [hunk 17]
```diff
@@ -0,0 +1,20 @@
+import {GuildModel} from "./models/guild.js";
+
+export class DatabaseService {
```
Comment (mkevenaar) [inline src/database/database.service.js:3]: I now get why and how you wanted to use the `GuildService` class and I agree.

Sorry for asking but would you be so kind to revert that to the `GuildService`

Thank you!

File: src/commands/admin/welcome.js (hunk 12 above)
Comment (Lucxjo) [reply src/commands/admin/welcome.js:73]: Okay, no problem. Thanks

**Review by Lucxjo — APPROVED** [review]
PR approved

File: src/database/database.service.js (hunk 17 above)
Comment (davidzwa) [reply src/database/database.service.js]: Absolutely! Please test the new commit :)

**Comment by mkevenaar** [comment]
@davidzwa your changes have been merged, thank you for your contribution!

**Comment by mkevenaar** [comment]
@all-contributors please add @davidzwa for bug
